/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

/**
 *
 * @author admin
 */
public class asdf extends javax.swing.JFrame {

    /**
     * Creates new form asdf
     */
    public asdf() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(asdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(asdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(asdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(asdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new asdf().setVisible(true);
	    }
	});
    }
    PreencherTabelaHome preenchertabelahome = new PreencherTabelaHome();
   PreencherTabelaComputadorNI preenchertabelacomputadorni = new PreencherTabelaComputadorNI();
   PreencherTabelaSupNI preenchertabelasupni = new PreencherTabelaSupNI();
    PreencherTabelaEstabNI preenchertabelaestabni = new PreencherTabelaEstabNI();
    PreencherTabelaImpressoraNI preenchertabelaimpressorani 
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	Editar editar = new Editar();
	editar.Edit(jText_patrimonio.getText(), jText_ip.getText(), jText_setor.getText(), 
	    jText_usuario.getText(), jText_marca.getText(), jText_sisope.getText(), 
	    jText_supcpu.getText(), jText_estab.getText(), jText_impressora.getText(), 
	    idSelecionado, patrimonioBtnEditar, supcpuBtnEditar, estabBtnEditar, impressoraBtnEditar);  
	
	PreencherTabelaComputador();

	if(!patrimonioBtnEditar.equals(jText_patrimonio.getText())){
	    Object opcoes[] = {"Mover para NI - 316", "Mover para 304", "Exclui-lo"}; //0 1 2
	    int selection = JOptionPane.showOptionDialog(
	    null, "O que deseja fazer com o CPU "+patrimonioBtnEditar+" ?", "",
	    0, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
	    patrimonioBtnEditar = jText_patrimonio.getText();
        }
	if(!supcpuBtnEditar.equals(jText_supcpu.getText())){
	    Object opcoes[] = {"Mover para NI - 316", "Mover para 304", "Exclui-lo"}; //0 1 2
	    int selection = JOptionPane.showOptionDialog(
	    null, "O que deseja fazer com o SUPORTE CPU "+supcpuBtnEditar+" ?", "",
	    0, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
	    supcpuBtnEditar = jText_supcpu.getText();
	}
	if(!estabBtnEditar.equals(jText_estab.getText())){
	    Object opcoes[] = {"Mover para NI - 316", "Mover para 304", "Exclui-lo"}; //0 1 2
	    int selection = JOptionPane.showOptionDialog(
	    null, "O que deseja fazer com o ESTABILIZADOR "+estabBtnEditar+" ?", "",
	    0, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
	    estabBtnEditar = jText_estab.getText();
        }
	if(!impressoraBtnEditar.equals(jText_impressora.getText())){
	    Object opcoes[] = {"Mover para NI - 316", "Mover para 304", "Exclui-la"}; //0 1 2
	    int selection = JOptionPane.showOptionDialog(
	    null, "O que deseja fazer com a IMPRESSORA "+impressoraBtnEditar+" ?", "",
	    0, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
	    impressoraBtnEditar = jText_impressora.getText();
	}
    }                                        
     /**
     * 
     * @PESQUISAS MENU DE SETORES
     */
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        PesquisarPeloSetor("'DIG'");
	Animacion.subir(0,-100,1,jPanel2);
	Animacion.subir(85,0,1,SetaMenuDeSetores);
	Animacion.subir(95,0,1,jScrollPane2);
    }                                         

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        PesquisarPeloSetor("'ATR'");
	Animacion.subir(0,-100,1,jPanel2);
	Animacion.subir(85,0,1,SetaMenuDeSetores);
	Animacion.subir(95,0,1,jScrollPane2);
    }                                         

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        PesquisarPeloSetor("'ACM'");
	Animacion.subir(0,-100,1,jPanel2);
	Animacion.subir(85,0,1,SetaMenuDeSetores);
	Animacion.subir(95,0,1,jScrollPane2);
    }                                         

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        PesquisarPeloSetor("'CM'");
	Animacion.subir(0,-100,1,jPanel2);
	Animacion.subir(85,0,1,SetaMenuDeSetores);
	Animacion.subir(95,0,1,jScrollPane2);
    }                                         

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        PesquisarPeloSetor("'ARQ'");
	Animacion.subir(0,-100,1,jPanel2);
	Animacion.subir(85,0,1,SetaMenuDeSetores);
	Animacion.subir(95,0,1,jScrollPane2);
    }                                         

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        PesquisarPeloSetor("'SCPMSO'");
	Animacion.subir(0,-100,1,jPanel2);
	Animacion.subir(85,0,1,SetaMenuDeSetores);
	Animacion.subir(95,0,1,jScrollPane2);
    }                                         
     /**
     * 
     * @UP / DOWN DO MENU DE SETORES/PESQUISA
     */
    private void SetaMenuDeSetoresMouseReleased(java.awt.event.MouseEvent evt) {                                                
	int position = SetaMenuDeSetores.getY();
	if(position > 0){
	    Animacion.subir(0,-100,1,jPanel2);
	    Animacion.subir(100,0,1,SetaMenuDeSetores);
	    Animacion.subir(95,0,1,jScrollPane2);
	}else{
	    Animacion.bajar(-110,0,1,jPanel2);
	    Animacion.bajar(0,100,1,SetaMenuDeSetores);
	    Animacion.bajar(0,95,1,jScrollPane2);
	}
    }                                               
     /**
     * 
     * @IR PARA HOME
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        parentPanel.removeAll();
        parentPanel.add(jPanelTabela);
        parentPanel.repaint();
        parentPanel.revalidate();
        PreencherTabelaComputador();
    }                                        
     /**
     * 
     * @EXCLUIR NA TABELA HOME
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Excluir excluir = new Excluir();
	excluir.exclui(jText_patrimonio.getText(), jText_ip.getText(), idSelecionado);
	PreencherTabelaComputador();
    }                                        
    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	PesquisasAvancada ps = new PesquisasAvancada();
	ps.asdf(jTableComputador, jComboBox_pesquisa.getSelectedItem().toString(), jTextField_pesquisa.getText());
	
	Animacion.subir(0,-100,1,jPanel2);
	Animacion.subir(85,0,1,SetaMenuDeSetores);
	Animacion.subir(95,0,1,jScrollPane2);
    }                                         

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        
     /**
     * 
     * @DUPLO CLICK TABELAS SALA NI
     */
    private void jTablecpuniMouseClicked(java.awt.event.MouseEvent evt) {                                         
	if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            int index = jTablecpuni.getSelectedRow();
	    model = (DefaultTableModel) jTablecpuni.getModel();	 
	    jText_cpu_ni.setText(model.getValueAt(index, 0).toString());
	    jText_marca_ni.setText(model.getValueAt(index, 1).toString());
	    jText_sisope_ni.setText(model.getValueAt(index, 2).toString());
        }
    }                                        

    private void jTablesupniMouseClicked(java.awt.event.MouseEvent evt) {                                         
	if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            int index = jTablesupni.getSelectedRow();
	    model = (DefaultTableModel) jTablesupni.getModel();	 
	    jText_supcpu_ni.setText(model.getValueAt(index, 0).toString());	  
        }
    }                                        

    private void jTableestabniMouseClicked(java.awt.event.MouseEvent evt) {                                           
	if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            int index = jTableestabni.getSelectedRow();
	    model = (DefaultTableModel) jTableestabni.getModel();	 
	    jText_estab_ni.setText(model.getValueAt(index, 0).toString());	  
        }
    }                                          

    private void jTableimpressoraniMouseClicked(java.awt.event.MouseEvent evt) {                                                
	if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            int index = jTableimpressorani.getSelectedRow();
	    model = (DefaultTableModel) jTableimpressorani.getModel();	 
	    jText_impressora_ni.setText(model.getValueAt(index, 0).toString());	  
        }
    }                                               

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
